path_classifiers:
  docs:
    - scripts/parse_tlds.py
  library:
    - "lib/*.min.*"
    - lib/math_parser.js
    - "typings/base*"
queries:
  - exclude: js/automatic-semicolon-insertion
  - exclude: js/incomplete-url-scheme-check
  - exclude: js/insecure-randomness
  - exclude: js/regex/always-matches
  - exclude: js/trivial-conditional
  - exclude: js/useless-expression
